Insert into estado (id, nome, sigla) values ('12', 'Acre', 'AC');
Insert into estado (id, nome, sigla) values ('27', 'Alagoas', 'AL');
Insert into estado (id, nome, sigla) values ('16', 'Amapá', 'AP');
Insert into estado (id, nome, sigla) values ('13', 'Amazonas', 'AM');
Insert into estado (id, nome, sigla) values ('29', 'Bahia', 'BA');
Insert into estado (id, nome, sigla) values ('23', 'Ceará', 'CE');
Insert into estado (id, nome, sigla) values ('53', 'Distrito Federal', 'entro-Oeste');
Insert into estado (id, nome, sigla) values ('32', 'Espírito Santo', 'ES');
Insert into estado (id, nome, sigla) values ('52', 'Goiás', 'GO');
Insert into estado (id, nome, sigla) values ('21', 'Maranhão', 'MA');
Insert into estado (id, nome, sigla) values ('51', 'Mato Grosso', 'MT');
Insert into estado (id, nome, sigla) values ('50', 'Mato Grosso do Sul', 'MS');
Insert into estado (id, nome, sigla) values ('31', 'Minas Gerais', 'MG');
Insert into estado (id, nome, sigla) values ('15', 'Pará', 'PA');
Insert into estado (id, nome, sigla) values ('25', 'Paraíba', 'PB');
Insert into estado (id, nome, sigla) values ('41', 'Paraná', 'PR');
Insert into estado (id, nome, sigla) values ('26', 'Pernambuco', 'PE');
Insert into estado (id, nome, sigla) values ('22', 'Piauí', 'PI');
Insert into estado (id, nome, sigla) values ('33', 'Rio de Janeiro', 'RJ');
Insert into estado (id, nome, sigla) values ('24', 'Rio Grande do Norte', 'RN');
Insert into estado (id, nome, sigla) values ('43', 'Rio Grande do Sul', 'RS');
Insert into estado (id, nome, sigla) values ('11', 'Rondônia', 'RO');
Insert into estado (id, nome, sigla) values ('14', 'Roraima', 'RR');
Insert into estado (id, nome, sigla) values ('42', 'Santa Catarina', 'SC');
Insert into estado (id, nome, sigla) values ('35', 'São Paulo', 'SP');
Insert into estado (id, nome, sigla) values ('28', 'Sergipe', 'SE');
Insert into estado (id, nome, sigla) values ('17', 'Tocantins', 'TO');
